# Generated by Django 2.1.2 on 2018-10-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARRCModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(blank=True, default='', max_length=50)),
                ('user', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
